### ISSUE TITLE
README.md has broken links.

### ISSUE THREAD

**Issue by V1cHu** [aashutoshrathi/HackerRank-Test-Case-Generator#11]
The README.md file for HackerRank-Test-Case-Generator has broken links for the different languages. Please fix it.

**Comment by aashutoshrathi** [comment]
Would you like to fix it? @V1cHu

**Comment by V1cHu** [comment]
Sure ! Will fix it and send a PR.

**Comment by V1cHu** [comment]
Looks like there a couple of duplicate PR's for the same.
