### ISSUE TITLE
Add Issue and PR Templates

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/HackerRank-Test-Case-Generator#12]

**Comment by aashutoshrathi** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by aashutoshrathi** [comment]
The label prediction failed because there are not enough labels. Three labels must have been set on at least three issues each.

The contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by anshumanv** [comment]
@aashutoshrathi ?

**Comment by ItsPugle** [comment]
@aashutoshrathi Are you okay for me too to create a Pull Request about this? I have a few ideas which might lend a hand towards making everything a little more simple.

**Comment by ItsPugle** [comment]
I'll take that as a no xd

**Comment by anshumanv** [comment]
Lol

**Comment by aashutoshrathi** [comment]
@ItsPugle Sorry, You were late, See other issues of your interest.
