### ISSUE TITLE
Desktop App Port for this application (GUI)

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/HackerRank-Test-Case-Generator#21]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Description

Convert This into Desktop App, by adding UI.

### Required Information
- [ ] Provide a **minimal code snippet** / example that reproduces the bug.
- [ ] Provide **screenshots** (if required)
- [x] Provide github **revision**

**Comment by gerardogalvez** [comment]
Any idea on how it should look like?

**Comment by aashutoshrathi** [comment]
A drag and drop/ browse the file menu at the start, and as soon as we load the file, it should load all the input values, asking for their limit/custom formula in responsive form and then a button, generate to finish the process.

**Comment by aashutoshrathi** [comment]
Ping @gerardogalvez Interested?

**Comment by gerardogalvez** [comment]
I'm really not that familiar GUI in Python, I'd prefer to leave this to someone else. Good luck!
