### ISSUE TITLE
Add Option generate files for CodeChef too.

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/HackerRank-Test-Case-Generator#53]
For CodeChef structure should be - Single folder with inputs and outputs line by line, since we have to upload test cases one by one there.

**Comment by agarwalrounak** [comment]
I will work on it.

**Comment by aashutoshrathi** [comment]
Sure @agarwalrounak

**Comment by prithaupadhyay** [comment]
@aashutoshrathi Is the issue still open for work? I would like to work on this.

**Comment by agarwalrounak** [comment]
@prithaupadhyay Go ahead! 
I was supposed to work on it but couldn't do so due to other commitments.

**Comment by aashutoshrathi** [comment]
Sure @prithaupadhyay Go ahead!
😉

**Comment by prithaupadhyay** [comment]
@aashutoshrathi Thank You. Already started working 👍
