### ISSUE TITLE
Add Option to generated files for HackerEarth too

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/HackerRank-Test-Case-Generator#54]
Use Hackerearth's zip format

**Comment by bhavesh-g** [comment]
I want to complete this. Please assign this to me, under GSSOC 2019.
thanks

**Comment by aashutoshrathi** [comment]
Sure

**Comment by ahegde3** [comment]
I have submitted the pull request towards it.

**Comment by aashutoshrathi** [comment]
@ahegde3 Please provide a demo and description on what pattern of tc's you used.
