### ISSUE TITLE
Create endpoint for solution file upload

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/HackerRank-Test-Case-Generator#62]
Create an API endpoint which takes solution file and executes compile script from code.

**Comment by mark-nakachon** [comment]
I am taking this issue and I am working on this

**Comment by aashutoshrathi** [comment]
Sure @mark-nakachon

**Comment by mark-nakachon** [comment]
Created a pull request please review it once

**Comment by aashutoshrathi** [comment]
On it @mark-nakachon
