### ISSUE TITLE
Improve UI of solution Upload page

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/HackerRank-Test-Case-Generator#75]
This is task is simple and is to make UI better for the upload page.
You can use CSS Libraries unless they are too heavy.

To be done after #73

**Comment by mark-nakachon** [comment]
i will take up this issue

**Comment by aashutoshrathi** [comment]
Assigned to @mark-nakachon

**Comment by mark-nakachon** [comment]
i made a PR please verify
