### ISSUE TITLE
Give links to all endpoints on homepage

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/HackerRank-Test-Case-Generator#77]
On https://tc-gen.herokuapp.com
i.e. The page to be redirected in /, should have links to all endpoints directly.
Eg: Upload File, Compile Files, Generate Testcases

**Comment by sweezy793** [comment]
I want to work on this.

**Comment by mark-nakachon** [comment]
@aashutoshrathi i will work on this issue

**Comment by aashutoshrathi** [comment]
@sweezy793 @mark-nakachon Since this is Kind of front-end task mainly.
Can you both propose a mock for the front page, I'll mark this one as the medium, then.
