### ISSUE TITLE
Set a common Nav and Footer for all web pages

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/HackerRank-Test-Case-Generator#80]
Add a common Header and Footer for all webpages.
Having consistent and clean UI.

**Comment by mark-nakachon** [comment]
I am taking up this issue

**Comment by aashutoshrathi** [comment]
Sure, proceed with PR

**Comment by mark-nakachon** [comment]
should i use any templating engine or just write code in html

**Comment by aashutoshrathi** [comment]
I recommend using the Template Engine.

**Comment by mark-nakachon** [comment]
Shall I use react

**Comment by aashutoshrathi** [comment]
Yeah, sure feel free to do so.
