### ISSUE TITLE
Execute scripts in Docker Environments when file uploading is done

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/HackerRank-Test-Case-Generator#87]

**Comment by mark-nakachon** [comment]
I am assigning this issue to myself

**Comment by aashutoshrathi** [comment]
Work on one at a time

**Comment by mark-nakachon** [comment]
I should execute tc_gen.py when user uploads a file as of now .
For this purpose shall I use spawn API in node is but I don't know whether it would be a efficient approach or not

**Comment by aashutoshrathi** [comment]
It won't be efficient but will work fine for MVP.
