### ISSUE TITLE
Add Demo GIF

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/HackerRank-Test-Case-Generator#9]
Add a GIF under How it works section, showing how One of Example Code Compiles and generate TCs

**Comment by bigpythonimish** [comment]
@aashutoshrathi  how do i run it? Gets stuck on the last iteration of ZIP generation

**Comment by aashutoshrathi** [comment]
Is it throwing some error @bigpythonimish?

**Comment by aashutoshrathi** [comment]
Check the demo, I have updated it.

**Comment by aashutoshrathi** [comment]
https://image.ibb.co/khsiyw/out.gif Here is GIF, your task is to minimize its size and add it to README

**Comment by sirjan13** [comment]
Can i Add this gif?
